"""Pure release, content, and runtime-load identities shared across Reef."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ArtifactRef:
    """Immutable binding from one release to its selected contents."""

    content_id: str
    release_id: str
    parent_release_id: str | None

    def __post_init__(self) -> None:
        if not isinstance(self.content_id, str) or not self.content_id:
            raise ValueError("content_id must be a non-empty string")
        if not isinstance(self.release_id, str) or not self.release_id:
            raise ValueError("release_id must be a non-empty string")
        if self.parent_release_id is not None and not isinstance(self.parent_release_id, str):
            raise ValueError("parent_release_id must be a string or null")


@dataclass(frozen=True)
class LiveWeightArtifactRef(ArtifactRef):
    """A release bound to one concrete serving-engine load of live weights."""

    runtime_load_id: str

    def __post_init__(self) -> None:
        super().__post_init__()
        if not isinstance(self.runtime_load_id, str) or not self.runtime_load_id:
            raise ValueError("runtime_load_id must be a non-empty string")


@dataclass(frozen=True)
class RuntimeLoadSpan:
    """Half-open response-token range generated by one runtime load."""

    start: int
    end: int
    runtime_load_id: str


def parse_runtime_load_spans(
    value: Any,
    *,
    field_name: str = "runtime_load_spans",
    response_length: int | None = None,
) -> tuple[RuntimeLoadSpan, ...]:
    """Return structurally valid contiguous half-open runtime-load spans."""
    if not isinstance(value, Sequence) or isinstance(value, str | bytes):
        raise ValueError(f"{field_name} must be a sequence")

    spans: list[RuntimeLoadSpan] = []
    cursor = 0
    for index, raw in enumerate(value):
        if not isinstance(raw, Mapping):
            raise ValueError(f"{field_name}[{index}] must be an object")
        try:
            start = raw["start"]
            end = raw["end"]
            runtime_load_id = raw["runtime_load_id"]
        except KeyError as exc:
            raise ValueError(f"invalid {field_name}[{index}]") from exc
        if (
            not isinstance(start, int)
            or isinstance(start, bool)
            or start != cursor
            or not isinstance(end, int)
            or isinstance(end, bool)
            or end <= start
            or not isinstance(runtime_load_id, str)
            or not runtime_load_id
        ):
            raise ValueError(f"invalid {field_name}[{index}]")
        spans.append(RuntimeLoadSpan(start=start, end=end, runtime_load_id=runtime_load_id))
        cursor = end

    if response_length is not None and cursor != response_length:
        raise ValueError(f"{field_name} cover {cursor} response tokens, expected {response_length}")
    return tuple(spans)


def encode_artifact_ref(ref: ArtifactRef) -> dict[str, Any]:
    """Encode a ref with an explicit discriminator for its concrete type."""
    value: dict[str, Any] = {
        "kind": "live_weights" if isinstance(ref, LiveWeightArtifactRef) else "artifact",
        "content_id": ref.content_id,
        "release_id": ref.release_id,
        "parent_release_id": ref.parent_release_id,
    }
    if isinstance(ref, LiveWeightArtifactRef):
        value["runtime_load_id"] = ref.runtime_load_id
    return value


def decode_artifact_ref(value: Mapping[str, Any]) -> ArtifactRef:
    """Decode the release/content/runtime-load ref wire format."""
    kind = value.get("kind")
    content_id = value.get("content_id")
    release_id = value.get("release_id")
    parent_release_id = value.get("parent_release_id")
    if kind not in ("artifact", "live_weights"):
        raise ValueError("artifact ref kind must be 'artifact' or 'live_weights'")
    if not isinstance(content_id, str) or not content_id:
        raise ValueError("artifact ref requires content_id")
    if not isinstance(release_id, str) or not release_id:
        raise ValueError("artifact ref requires release_id")
    if parent_release_id is not None and not isinstance(parent_release_id, str):
        raise ValueError("artifact ref parent_release_id must be a string or null")
    if kind == "artifact":
        if "runtime_load_id" in value:
            raise ValueError("artifact ref must not carry runtime_load_id")
        return ArtifactRef(content_id, release_id, parent_release_id)
    runtime_load_id = value.get("runtime_load_id")
    if not isinstance(runtime_load_id, str) or not runtime_load_id:
        raise ValueError("live-weight artifact ref requires a non-empty runtime_load_id")
    return LiveWeightArtifactRef(content_id, release_id, parent_release_id, runtime_load_id)


__all__ = [
    "ArtifactRef",
    "LiveWeightArtifactRef",
    "RuntimeLoadSpan",
    "decode_artifact_ref",
    "encode_artifact_ref",
    "parse_runtime_load_spans",
]
